language: java
jdk:
  - oraclejdk7
  - openjdk7
install: "travis_retry mvn install -DskipTests=true -f pom-libs.xml -B -V"
script: "travis_retry mvn install -Pproduct -Psdk -B -V"
env:  MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  only:
    - luna-support
    - master
    - udig-gt-11-snapshot
