language: java
jdk:
  - oraclejdk7
  - openjdk7
script:
  - travis_wait mvn clean install -f pom-libs.xml
  - travis_wait mvn clean install -Pproduct -Psdk
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  only:
    - luna-support
    - master
    - udig-gt-11-snapshot
