language: java
jdk:
  - openjdk7 # just run openJdk - oraclejdk7
env:
  global:
    - MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
    - TRAVIS_PYTHON_VERSION="2.7"
install:
  - "travis_retry sudo pip install -q sphinx==1.1.3 --use-mirrors || (cat /home/travis/.pip/pip.log; false)"
  - "travis_wait mvn install -DskipTests=true -f pom-libs.xml -B -V" #download dependencies

script: "travis_wait mvn install -Pproduct -Psdk -Pdocs -B -V -X"

notifications:
  email:
    on_success: never
    on_failure: never
  irc:
    channels: "irc.freenode.org#udig"
    on_success: change
    on_failure: always
#    template: "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    template: "%{repository} (%{branch}:%{commit}): %{message} (%{build_url})"
branches:
  only:
    - luna-support
    - master
